;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Weapon.Fire",DevComment="원거리 공격 Ability 태그")
+GameplayTagList=(Tag="Ability.Weapon.MeleeAttack",DevComment="근접 공격 Ability 태그")
+GameplayTagList=(Tag="Event.Combat.Hit",DevComment="AnimNotify → Ability 히트 이벤트")
+GameplayTagList=(Tag="Data.Combat.Damage",DevComment="SetByCaller 데미지 전달용 태그")

