;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

+GameplayTagList=(Tag="State.Combat.Attacking",DevComment="Attacking State Tag")
+GameplayTagList=(Tag="State.Combat.Dead",DevComment="Dead State Tag")
+GameplayTagList=(Tag="State.Movement.Moving",DevComment="이동 상태 태그")
+GameplayTagList=(Tag="State.Movement.Rotating",DevComment="회전 상태 태그")
+GameplayTagList=(Tag="Ability.Active.Fire",DevComment="원거리 공격 Ability 태그")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack",DevComment="근접 공격 Ability 태그")
+GameplayTagList=(Tag="Ability.Active.Mining",DevComment="채굴 Ability 태그")
+GameplayTagList=(Tag="Ability.Active.Jetpack",DevComment="Jetpack Ability 태그")
+GameplayTagList=(Tag="Ability.Active.Reload",DevComment="Reload Ability 태그")
+GameplayTagList=(Tag="Data.Combat.Damage",DevComment="SetByCaller 데미지 전달용 태그")
+GameplayTagList=(Tag="Data.Combat.Heal",DevComment="SetByCaller 회복 전달용 태그")
+GameplayTagList=(Tag="Data.Ammo.Reload",DevComment="SetByCaller 장전 전달용 태그")
+GameplayTagList=(Tag="Event.Combat.Hit",DevComment="히트 이벤트")
+GameplayTagList=(Tag="Event.Combat.Dead",DevComment="히트 이벤트")
+GameplayTagList=(Tag="Event.Weapon.Switch",DevComment="무기 변경 태그")
+GameplayTagList=(Tag="Weapon.Equipped.Melee",DevComment="근접 장비 태그")
+GameplayTagList=(Tag="Weapon.Equipped.Mining",DevComment="채굴 장비 태그")
+GameplayTagList=(Tag="Weapon.Equipped.Ranged",DevComment="원거리 장비 태그")
+GameplayTagList=(Tag="Weapon.Equipped.Jetpack",DevComment="Jetpack 장비 태그")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire",DevComment="Weapon fire effect")
+GameplayTagList=(Tag="GameplayCue.Combat.Dead",DevComment="Weapon fire effect")



